In [27]:
import numpy as np
import pandas as pd
from tqdm import tqdm
from transformers import AutoTokenizer

In [2]:
pl = pd.read_pickle('../data/train_pl_2022.pkl')
pl

,pn_num,case_num,pn_history,feature_num,feature_text,fold,id,location,annotation,annotation_length
0,0,0,"17-year-old male, has come to the student heal...",0,Family-history-of-MI-OR-Family-history-of-myoc...,4,00000_000,[553 566],[father had MI],1
1,0,0,"17-year-old male, has come to the student heal...",1,Family-history-of-thyroid-disorder,2,00000_001,[576 597],[mother has thyroid dz],1
2,0,0,"17-year-old male, has come to the student heal...",2,Chest-pressure,3,00000_002,[],[],0
3,0,0,"17-year-old male, has come to the student heal...",3,Intermittent-symptoms,4,00000_003,[216 228],[intermittent],1
4,0,0,"17-year-old male, has come to the student heal...",4,Lightheaded,0,00000_004,[],[],0
...,...,...,...,...,...,...,...,...,...,...
612597,95334,9,patient is a 20 yo F who presents with a heada...,912,Family-history-of-migraines,3,95334_912,"[794 796, 798 811]","[FH, mom migraines]",2
612598,95334,9,patient is a 20 yo F who presents with a heada...,913,Female,2,95334_913,[19 20],[F],1
612599,95334,9,patient is a 20 yo F who presents with a heada...,914,Photophobia,2,95334_914,[486 504],[sensitive to light],1
612600,95334,9,patient is a 20 yo F who presents with a heada...,915,No-known-illness-contacts,0,95334_915,[],[],0
612601,95334,9,patient is a 20 yo F who presents with a heada...,916,Subjective-fever,4,95334_916,[424 432],[feverish],1

In [51]:
tokenizer = AutoTokenizer.from_pretrained('roberta-large-mnli', trim_offsets=False)

In [42]:
text_lens = []
for text in tqdm(pl.pn_history.unique()):
    encoded = tokenizer(text, add_special_tokens=True)
    text_lens.append(len(encoded['input_ids']))
max(lens)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 41146/41146 [00:15<00:00, 2689.95it/s]

435

In [43]:
fea_lens = []
for text in tqdm(pl.feature_text.unique()):
    encoded = tokenizer(text, add_special_tokens=True)
    fea_lens.append(len(encoded['input_ids']))
max(fea_lens)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 131/131 [00:00<00:00, 17984.81it/s]

30

In [53]:
train = pd.read_pickle('../data/train_processed.pkl')
train

,id,case_num,pn_num,feature_num,annotation,location,feature_text,pn_history,annotation_length,fold
0,00016_000,0,16,0,[dad with recent heart attcak],[696 724],Family-history-of-MI-OR-Family-history-of-myoc...,HPI: 17yo M presents with palpitations. Patien...,1,4
1,00016_001,0,16,1,"[mom with ""thyroid disease]",[668 693],Family-history-of-thyroid-disorder,HPI: 17yo M presents with palpitations. Patien...,1,4
2,00016_002,0,16,2,[chest pressure],[203 217],Chest-pressure,HPI: 17yo M presents with palpitations. Patien...,1,4
3,00016_003,0,16,3,"[intermittent episodes, episode]","[70 91, 176 183]",Intermittent-symptoms,HPI: 17yo M presents with palpitations. Patien...,2,4
4,00016_004,0,16,4,[felt as if he were going to pass out],[222 258],Lightheaded,HPI: 17yo M presents with palpitations. Patien...,1,4
...,...,...,...,...,...,...,...,...,...,...
14295,95333_912,9,95333,912,[],[],Family-history-of-migraines,Stephanie madden is a 20 year old woman compla...,0,4
14296,95333_913,9,95333,913,[],[],Female,Stephanie madden is a 20 year old woman compla...,0,4
14297,95333_914,9,95333,914,[photobia],[274 282],Photophobia,Stephanie madden is a 20 year old woman compla...,1,4
14298,95333_915,9,95333,915,[no sick contacts],[421 437],No-known-illness-contacts,Stephanie madden is a 20 year old woman compla...,1,4
14299,95333_916,9,95333,916,[Subjective fever],[314 330],Subjective-fever,Stephanie madden is a 20 year old woman compla...,1,4

In [54]:
train.loc[0, 'location'], pl.loc[0, 'location']

(['696 724'], ['553 566'])

In [55]:
fold = 0
train_df = train[train['fold'] != fold].reset_index(drop=True)
train_df = pd.concat([train_df, pl[pl['fold'] == fold]]).reset_index(drop=True)
train_df

,id,case_num,pn_num,feature_num,annotation,location,feature_text,pn_history,annotation_length,fold
0,00016_000,0,16,0,[dad with recent heart attcak],[696 724],Family-history-of-MI-OR-Family-history-of-myoc...,HPI: 17yo M presents with palpitations. Patien...,1,4
1,00016_001,0,16,1,"[mom with ""thyroid disease]",[668 693],Family-history-of-thyroid-disorder,HPI: 17yo M presents with palpitations. Patien...,1,4
2,00016_002,0,16,2,[chest pressure],[203 217],Chest-pressure,HPI: 17yo M presents with palpitations. Patien...,1,4
3,00016_003,0,16,3,"[intermittent episodes, episode]","[70 91, 176 183]",Intermittent-symptoms,HPI: 17yo M presents with palpitations. Patien...,2,4
4,00016_004,0,16,4,[felt as if he were going to pass out],[222 258],Lightheaded,HPI: 17yo M presents with palpitations. Patien...,1,4
...,...,...,...,...,...,...,...,...,...,...
133956,95332_911,9,95332,911,[],[],Meningococcal-vaccine-status-unknown,Ms. Madden is a 20yo female who presents with ...,0,0
133957,95332_915,9,95332,915,[No sick contacts],[542 558],No-known-illness-contacts,Ms. Madden is a 20yo female who presents with ...,1,0
133958,95334_902,9,95334,902,[yesterday],[238 247],1-day-duration-OR-2-days-duration,patient is a 20 yo F who presents with a heada...,1,0
133959,95334_905,9,95334,905,[],[],Neck-pain,patient is a 20 yo F who presents with a heada...,0,0
133960,95334_915,9,95334,915,[],[],No-known-illness-contacts,patient is a 20 yo F who presents with a heada...,0,0

In [56]:
len(train) //5 * 4 + len(pl)//5

133960

In [57]:
train_df.groupby('fold').count()

,id,case_num,pn_num,feature_num,annotation,location,feature_text,pn_history,annotation_length
fold,,,,,,,,,
0,122521,122521,122521,122521,122521,122521,122521,122521,122521
1,2860,2860,2860,2860,2860,2860,2860,2860,2860
2,2860,2860,2860,2860,2860,2860,2860,2860,2860
3,2860,2860,2860,2860,2860,2860,2860,2860,2860
4,2860,2860,2860,2860,2860,2860,2860,2860,2860